services:
  - postgresql
before_script:
  - psql -c 'create database ex_admin_test;' -U postgres
  - nohup phantomjs --wd &
language: elixir
elixir:
  - 1.4.2
  - 1.4.1
  - 1.4.0
  - 1.3.4
  - 1.3.3
  - 1.3.2
  - 1.3.1
otp_release:
  - 19.3
  - 19.2
  - 19.1
  - 19.0
  - 18.3
  - 18.2.1
sudo: false
script: mix test --include integration:true
notification:
  recipients:
    - smpallen99@yahoo.com
